#!/usr/bin/env bash
set -euo pipefail

USERD="$HOME/.config/systemd/user"
PROTECTED=(brainbox-portal zyrkel reprofleet)
log(){ printf '\033[36m[governor]\033[0m %s\n' "$*"; }
. "$(dirname "$(readlink -f "$0")")/lib-service.sh"

memtotal_mib=$(awk '/^MemTotal:/{printf "%d", $2/1024}' /proc/meminfo)
swaptotal_mib=$(awk '/^SwapTotal:/{printf "%d", $2/1024}' /proc/meminfo)
imin=$(awk -v t=$memtotal_mib 'BEGIN{v=int(t*0.16); print (v<1024?1024:v)}')
ilow=$(awk -v t=$memtotal_mib 'BEGIN{v=int(t*0.26); print (v<1800?1800:v)}')
bhigh=$(awk -v t=$memtotal_mib 'BEGIN{print int(t*0.50)}')
bmax=$(awk -v t=$memtotal_mib 'BEGIN{print int(t*0.60)}')
bswap=$(awk -v s=$swaptotal_mib 'BEGIN{print int(s*0.50)}')
log "capacity: RAM=${memtotal_mib}MiB swap=${swaptotal_mib}MiB"
log "interactive: MemoryMin=${imin}M MemoryLow=${ilow}M | batch: High=${bhigh}M Max=${bmax}M SwapMax=${bswap}M"

svc_announce

case "$(svc_mgr)" in

pninit)
  SITE_CONF="${SITE_CONF:-$PN_ETC/brainbox/site.conf}"
  log "Betreiberabsicht: $SITE_CONF (fehlende Schluessel werden ergaenzt, vorhandene bleiben)"
  svc_envfile_set "$SITE_CONF" PN_BATCH_HIGH_MIB "$bhigh"
  svc_envfile_set "$SITE_CONF" PN_BATCH_MAX_MIB  "$bmax"

  PN_CGTREE="${PN_CGTREE:-/usr/local/bin/pn-cgtree}"
  if [ -x "$PN_CGTREE" ]; then
    if svc_dry_run; then
      svc_dry "sudo $PN_CGTREE   (baut pn.slice/{critical,batch,interactive}, idempotent)"
    else
      svc_priv "$PN_CGTREE" || log "WARN: pn-cgtree meldete einen Fehler (fail-safe: Box bootet)"
    fi
  else
    svc_warn "$PN_CGTREE fehlt — ohne delegierten pn.slice-Baum lehnt pnd governte Jobs mit rc126 ab."
  fi

  for t in pn-critical.slice pn-batch.slice pn-misc.slice pn.slice; do
    if [ -d "/sys/fs/cgroup/$t" ]; then
      log "  Tier vorhanden: $t  (memory.max=$(cat "/sys/fs/cgroup/$t/memory.max" 2>/dev/null || echo '?'))"
    else
      svc_warn "  Tier FEHLT: /sys/fs/cgroup/$t"
    fi
  done

  for svc in "${PROTECTED[@]}" phantom-portal; do
    if grep -qE "^[[:space:]]*${svc}\|" "$PN_INIT_CONF" 2>/dev/null; then
      if grep -qE "^[[:space:]]*${svc}\|[^|]*sacred" "$PN_INIT_CONF" 2>/dev/null; then
        log "  geschuetzt: $svc (sacred -> pn-critical.slice)"
      else
        svc_warn "  $svc steht in $PN_INIT_CONF, aber OHNE 'sacred' -> pn-misc.slice (engster Tier)."
        svc_warn "    Schuetzen mit: pnctl add $svc 'sacred <bisherige flags>' <bisheriges argv>"
      fi
    fi
  done
  log "done. Nachsehen mit: pnctl list  |  cat /sys/fs/cgroup/pn-batch.slice/memory.max"
  ;;

systemd)
  mkdir -p "$USERD"
  cat > "$USERD/pn-interactive.slice" <<EOF
# GENERATED by portioneer install (Layer A). Do not edit by hand; re-run install.
[Unit]
Description=portioneer protected interactive services
Before=pn-batch.slice
[Slice]
MemoryAccounting=yes
MemoryMin=${imin}M
MemoryLow=${ilow}M
# H4 (scheduler-gap-analysis): keep interactive OUT of swap so the portal/voice never eat
# swap-in latency; PSI/oomd still has the batch swap band below as its reaction runway.
MemorySwapMax=0
CPUAccounting=yes
CPUWeight=100
IOAccounting=yes
IOWeight=100
TasksAccounting=yes
EOF

  cat > "$USERD/pn-batch.slice" <<EOF
# GENERATED by portioneer install (Layer A). Do not edit by hand; re-run install.
[Unit]
Description=portioneer governed batch work
[Slice]
MemoryAccounting=yes
MemoryHigh=${bhigh}M
MemoryMax=${bmax}M
MemorySwapMax=${bswap}M
CPUAccounting=yes
CPUWeight=50
IOAccounting=yes
IOWeight=50
TasksAccounting=yes
TasksMax=4096
ManagedOOMMemoryPressure=kill
ManagedOOMMemoryPressureLimit=80%
EOF

  for svc in "${PROTECTED[@]}"; do
    if ! systemctl --user cat "$svc.service" >/dev/null 2>&1; then
      log "skip $svc (no such user unit)"; continue
    fi
    d="$USERD/$svc.service.d"; mkdir -p "$d"
    f="$d/pn.conf"
    [ -f "$f" ] && ! grep -q 'portioneer drop-in' "$f" && cp -n "$f" "$f.pn-bak"
    cat > "$f" <<EOF
# portioneer drop-in — protect $svc (interactive slice + last OOM pick).
[Service]
Slice=pn-interactive.slice
OOMScoreAdjust=-800
MemoryAccounting=yes
EOF
    log "protected $svc"
  done

  if svc_dry_run; then
    svc_dry "systemctl --user daemon-reload; start pn-interactive.slice pn-batch.slice; restart ${PROTECTED[*]}"
  else
    systemctl --user daemon-reload
    systemctl --user start pn-interactive.slice pn-batch.slice 2>/dev/null || true
    for svc in "${PROTECTED[@]}"; do
      systemctl --user cat "$svc.service" >/dev/null 2>&1 || continue
      systemctl --user restart "$svc.service" || log "WARN: restart $svc failed"
    done
  fi
  log "done. verify with: systemctl --user status pn-interactive.slice pn-batch.slice"
  ;;

none)
  svc_skip "Governor-Schicht: weder pn-init-Tiers noch systemd-Slices — es wird NICHTS gedeckelt."
  svc_skip "  Ohne Deckel ist Layer A wirkungslos; pnd admittiert dann ungeschuetzt."
  ;;
esac
