#!/usr/bin/env bash
set -euo pipefail
REPO="$HOME/portioneer"
USERD="$HOME/.config/systemd/user"
BIN="$HOME/.local/bin"
log(){ printf '\033[36m[daemon]\033[0m %s\n' "$*"; }
. "$(dirname "$(readlink -f "$0")")/lib-service.sh"

mkdir -p "$BIN" "$USERD" "$HOME/.local/share/portioneer/logs"
chmod +x "$REPO/tools/pn" "$REPO/tools/pnd" "$REPO/tools/pn-llmd" 2>/dev/null || true

ln -sf "$REPO/tools/pn" "$BIN/pn"
log "linked $BIN/pn -> $REPO/tools/pn"

cpus="$(nproc)"
ram_mb="$(awk '/MemTotal/{print int($2/1024)}' /proc/meminfo)"
pn_floor=$(( ram_mb * 16 / 100 )); [ "$pn_floor" -lt 1500 ] && pn_floor=1500
pn_high=$(( ram_mb * 38 / 100 ))
pn_maxc=$(( cpus + 2 ))
log "pnd tuning: MEM_FLOOR=${pn_floor} BATCH_HIGH=${pn_high} MAX_CONCURRENT=${pn_maxc} RESERVED_CORES=1 (cpu_budget=$(( cpus - 1 )))"

svc_announce

case "$(svc_mgr)" in

pninit)
  PND_ENVFILE="${PND_ENVFILE:-$PN_ETC/brainbox/pnd.env}"
  PND_SOCK="${PND_SOCK:-${XDG_RUNTIME_DIR:-/run/user/$(id -u)}/pnd.sock}"
  log "envfile: $PND_ENVFILE (fehlende Schluessel werden ergaenzt, vorhandene bleiben)"
  svc_envfile_set "$PND_ENVFILE" PN_MEM_FLOOR      "$pn_floor"
  svc_envfile_set "$PND_ENVFILE" PN_BATCH_HIGH     "$pn_high"
  svc_envfile_set "$PND_ENVFILE" PN_MAX_CONCURRENT "$pn_maxc"
  svc_envfile_set "$PND_ENVFILE" PN_RESERVED_CORES 1
  svc_declare pnd "sacred pnd user=$(id -u) envfile=$PND_ENVFILE pndsock=$PND_SOCK" \
              "$REPO/tools/pnd"
  ;;

systemd)
  cp "$REPO/systemd/pnd.service" "$USERD/pnd.service"
  mkdir -p "$USERD/pnd.service.d"
  cat > "$USERD/pnd.service.d/10-tuning.conf" <<EOF
# GENERATED by portioneer install — host-relative resource-governor tuning.
[Service]
Environment=PN_MEM_FLOOR=${pn_floor}
Environment=PN_BATCH_HIGH=${pn_high}
Environment=PN_MAX_CONCURRENT=${pn_maxc}
Environment=PN_RESERVED_CORES=1
EOF
  if svc_dry_run; then
    svc_dry "systemctl --user daemon-reload; systemctl --user enable --now pnd.service"
  else
    systemctl --user daemon-reload
    systemctl --user enable --now pnd.service
  fi
  ;;

none)
  svc_skip "pnd wird nicht als Dienst eingerichtet — weder pn-init noch ein systemd-User-Bus da."
  svc_skip "  Vordergrund-Start zum Pruefen: $REPO/tools/pnd"
  ;;
esac

if svc_dry_run || [ "$(svc_mgr)" = "none" ]; then
  exit 0
fi
sleep 1
if svc_active pnd; then
  log "pnd active. ping:"; "$BIN/pn" ping || true
else
  log "WARN: pnd not active"
  svc_diag pnd
  case "$(svc_mgr)" in
    pninit)  log "  Protokoll: die pn-init-Konsole (ttyS0) bzw. \`pnctl list\`" ;;
    systemd) log "  Protokoll: journalctl --user -u pnd -n 30" ;;
  esac
fi
