package provision

import (
	"fmt"
	"strings"
	"text/template"

	"github.com/schlein-lab/brainarbeit/installer/internal/detect"
	"github.com/schlein-lab/brainarbeit/installer/internal/sizing"
	"github.com/schlein-lab/brainarbeit/installer/internal/state"
)

type DomainParams struct {
	Name      string
	UUID      string
	VRAMMiB   int
	VCPU      int
	Arch      string
	Machine   string
	RootImg   string
	DataImg   string
	BridgeDev string
	NATNet    string
}

const domainTmpl = `<!-- generated by pn-factory (DRY-RUN: NOT defined) -->
<domain type='kvm'>
  <name>{{.Name}}</name>
  <uuid>{{.UUID}}</uuid>
  <memory unit='MiB'>{{.VRAMMiB}}</memory>
  <currentMemory unit='MiB'>{{.VRAMMiB}}</currentMemory>
  <vcpu placement='static'>{{.VCPU}}</vcpu>
  <os>
    <type arch='{{.Arch}}' machine='{{.Machine}}'>hvm</type>
    <boot dev='hd'/>
  </os>
  <features>
    <acpi/>
    <apic/>
  </features>
  <cpu mode='host-passthrough' check='none' migratable='off'/>
  <clock offset='utc'>
    <timer name='rtc' tickpolicy='catchup'/>
    <timer name='pit' tickpolicy='delay'/>
    <timer name='hpet' present='no'/>
  </clock>
  <on_poweroff>destroy</on_poweroff>
  <on_reboot>restart</on_reboot>
  <on_crash>restart</on_crash>
  <devices>
    <emulator>/usr/bin/qemu-system-{{.Arch}}</emulator>
    <disk type='file' device='disk'>
      <driver name='qemu' type='qcow2' cache='none' io='native'/>
      <source file='{{.RootImg}}'/>
      <target dev='vda' bus='virtio'/>
    </disk>
    <disk type='file' device='disk'>
      <driver name='qemu' type='qcow2' cache='none' io='native'/>
      <source file='{{.DataImg}}'/>
      <target dev='vdb' bus='virtio'/>
      <serial>brainarbeit-data</serial>
    </disk>
{{if .BridgeDev}}    <interface type='bridge'>
      <source bridge='{{.BridgeDev}}'/>
      <model type='virtio'/>
    </interface>
{{else}}    <interface type='network'>
      <source network='{{.NATNet}}'/>
      <model type='virtio'/>
    </interface>
{{end}}    <serial type='pty'>
      <target type='isa-serial' port='0'/>
    </serial>
    <console type='pty'>
      <target type='serial' port='0'/>
    </console>
    <!-- LOAD-BEARING: real hardware reset for the L0 watchdog path -->
    <watchdog model='i6300esb' action='reset'/>
    <memballoon model='virtio'/>
    <rng model='virtio'>
      <backend model='random'>/dev/urandom</backend>
    </rng>
  </devices>
</domain>
`

var domainTemplate = template.Must(template.New("domain").Parse(domainTmpl))

func DomainParamsFrom(name, arch, bridge string, spec sizing.Spec, dataDir string) DomainParams {
	machine := "q35"
	if arch == "aarch64" || arch == "arm64" {
		arch, machine = "aarch64", "virt"
	} else {
		arch = "x86_64"
	}
	return DomainParams{
		Name:      name,
		UUID:      deterministicUUID(name),
		VRAMMiB:   spec.VRAMMiB,
		VCPU:      spec.VCPU,
		Arch:      arch,
		Machine:   machine,
		RootImg:   dataDir + "/" + name + "-root-a.qcow2",
		DataImg:   dataDir + "/" + name + "-data.qcow2",
		BridgeDev: bridge,
		NATNet:    "default",
	}
}

func DomainXML(p DomainParams) (string, error) {
	var b strings.Builder
	if err := domainTemplate.Execute(&b, p); err != nil {
		return "", err
	}
	return b.String(), nil
}

func deterministicUUID(name string) string {
	var h uint64 = 1469598103934665603
	for i := 0; i < len(name); i++ {
		h ^= uint64(name[i])
		h *= 1099511628211
	}

	var b [16]byte
	for i := 0; i < 16; i++ {
		b[i] = byte(h >> (uint(i%8) * 8))
		if i%8 == 7 {
			h *= 1099511628211
		}
	}
	b[6] = (b[6] & 0x0f) | 0x50
	b[8] = (b[8] & 0x3f) | 0x80
	return fmt.Sprintf("%02x%02x%02x%02x-%02x%02x-%02x%02x-%02x%02x-%02x%02x%02x%02x%02x%02x",
		b[0], b[1], b[2], b[3], b[4], b[5], b[6], b[7], b[8], b[9], b[10], b[11], b[12], b[13], b[14], b[15])
}

type libvirtDriver struct{}

func (libvirtDriver) Backend() detect.Backend { return detect.BackendLibvirt }

func (libvirtDriver) Plan(ctx BackendContext) BackendPlan {
	dp := DomainParamsFrom(ctx.Name, ctx.Arch, ctx.Net.Bridge, ctx.Spec, ctx.DataDir)
	xml, err := DomainXML(dp)
	if err != nil {
		xml = "<!-- domain XML generation failed: " + err.Error() + " -->"
	}
	steps := []string{
		"qemu-img convert -O qcow2 <verified golden image> " + dp.RootImg,
		fmt.Sprintf("qemu-img create -f qcow2 %s %dG   (separate btrfs DATA disk)", dp.DataImg, ctx.Spec.DataGiB),
		"virsh define <(generated domain XML)   # i6300esb watchdog action=reset — the validated runtest.sh path",
		"virsh start " + dp.Name,
		"virsh console " + dp.Name + "   # first-boot watchdog self-test confirms the host hard-resets the guest",
	}
	st := []StateEntry{networkStateEntry(ctx)}
	st = append(st, imageStateEntries(ctx)...)
	st = append(st,
		StateEntry{Action: state.ActDefineDomain, Target: dp.Name, Reverse: "virsh undefine " + dp.Name, Meta: map[string]string{"uuid": dp.UUID}},
		StateEntry{Action: state.ActStartDomain, Target: dp.Name, Reverse: "virsh destroy " + dp.Name},
	)
	return BackendPlan{
		Backend:  detect.BackendLibvirt,
		Title:    "libvirt/KVM domain (i6300esb watchdog, separate DATA disk)",
		Maturity: MaturityDryRun,
		Steps:    steps,
		State:    st,
		Degraded: DegradeFor(ctx.Report),
		Extra:    []string{"domain XML rendered (would be `virsh define`d):\n" + indentBlock(xml, "      ")},
	}
}

type qemuRawDriver struct{}

func (qemuRawDriver) Backend() detect.Backend { return detect.BackendQemuRaw }

func (qemuRawDriver) Plan(ctx BackendContext) BackendPlan {
	dp := DomainParamsFrom(ctx.Name, ctx.Arch, ctx.Net.Bridge, ctx.Spec, ctx.DataDir)
	emu := "qemu-system-" + dp.Arch
	netArg := "-netdev user,id=n0,hostfwd=tcp::22000-:22,hostfwd=tcp::8443-:443 -device virtio-net,netdev=n0"
	if dp.BridgeDev != "" {
		netArg = "-netdev bridge,id=n0,br=" + dp.BridgeDev + " -device virtio-net,netdev=n0"
	}
	cmdline := fmt.Sprintf(
		"%s -machine %s,accel=kvm -cpu host -m %d -smp %d "+
			"-drive file=%s,if=virtio,cache=none -drive file=%s,if=virtio,cache=none,serial=brainarbeit-data "+
			"-device i6300esb,id=wd -watchdog-action reset "+
			"%s -nographic -serial pty",
		emu, dp.Machine, dp.VRAMMiB, dp.VCPU, dp.RootImg, dp.DataImg, netArg)
	unit := "pn-brainarbeit.service (Restart=on-failure, ExecStart=" + emu + " ...)"
	steps := []string{
		"qemu-img convert -O qcow2 <verified golden image> " + dp.RootImg,
		fmt.Sprintf("qemu-img create -f qcow2 %s %dG", dp.DataImg, ctx.Spec.DataGiB),
		"write host-side supervisor unit " + unit + " (no libvirtd → systemd is the supervisor)",
		"systemctl enable --now pn-brainarbeit.service   # launches:",
		"  " + cmdline,
		"first-boot watchdog self-test over the -serial pty (auto-softdog fallback if i6300esb is a no-op)",
	}
	st := []StateEntry{networkStateEntry(ctx)}
	st = append(st, imageStateEntries(ctx)...)
	st = append(st,
		StateEntry{Action: state.ActDefineDomain, Target: "pn-brainarbeit.service", Reverse: "systemctl disable --now pn-brainarbeit.service && rm /etc/systemd/system/pn-brainarbeit.service"},
		StateEntry{Action: state.ActStartDomain, Target: dp.Name, Reverse: "systemctl stop pn-brainarbeit.service"},
	)
	return BackendPlan{
		Backend:  detect.BackendQemuRaw,
		Title:    "raw supervised qemu -accel kvm (no libvirtd; systemd supervisor)",
		Maturity: MaturityDryRun,
		Steps:    steps,
		State:    st,
		Degraded: DegradeFor(ctx.Report),
		Extra:    []string{"host-side supervisor: " + unit},
	}
}

func init() {
	register(libvirtDriver{})
	register(qemuRawDriver{})
}

func indentBlock(s, pad string) string {
	var b strings.Builder
	for _, line := range strings.Split(strings.TrimRight(s, "\n"), "\n") {
		b.WriteString(pad)
		b.WriteString(line)
		b.WriteString("\n")
	}
	return strings.TrimRight(b.String(), "\n")
}
