
[Content]
KernelCommandLine=
        init=/usr/lib/brainarbeit/pn-init
        console=ttyS0
        console=tty0
        panic=-1
        pn.crashmax=3
        pn.fullsystem
        pn.devmgr=mdev
        loglevel=4
KernelModulesInclude=
        i6300esb
        softdog
        btrfs
        erofs
        dm-verity
        overlay
