
[Content]
Packages=
        sysvinit-core
        systemd-standalone-sysusers
        dbus
        libpam-modules
        linux-image-amd64
        grub-efi-amd64
        btrfs-progs
        dosfstools
        e2fsprogs
        erofs-utils
        cryptsetup
        openssh-server
        ca-certificates
        iproute2
        udhcpc
        nftables
        avahi-daemon
        kmod
        busybox

        python3
        python3-venv
        git
        sqlite3
        age
        tmux

RemovePackages=
        gnome-shell
        mutter
        gnome-session
        gnome-session-bin
        gdm3
        gjs
        tracker
        tracker-miner-fs
        evolution
        evolution-data-server
        gnome-online-accounts
        gvfs
        gvfs-daemons
        gnome-remote-desktop
        systemd
        systemd-sysv
        systemd-boot
        systemd-resolved
        systemd-timesyncd
        udev
        libnss-systemd
        libpam-systemd
