#!/usr/bin/env python3

import struct
import sys
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    sys.exit("PIL/Pillow required (build-time only): pip install pillow")

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "assets" / "shell" / "eclipse-corona.png"
OUT_BIN = ROOT / "src" / "shell_sphere.bin"
OUT_RS = ROOT / "src" / "shell_sphere.rs"

SPRITE = 680

R_DISC = 232.0
R_FADE = 510.0

def main() -> None:
    im = Image.open(SRC).convert("RGB")
    w, h = im.size
    cx, cy = w / 2.0, h / 2.0
    src = im.load()

    rgba = Image.new("RGBA", (w, h))
    dst = rgba.load()
    for y in range(h):
        dy = y - cy
        for x in range(w):
            r, g, b = src[x, y]
            dx = x - cx
            rad = (dx * dx + dy * dy) ** 0.5
            if rad <= R_DISC:
                a = 255
            else:

                lum = (r * 0.299 + g * 0.587 + b * 0.114) / 255.0
                if rad >= R_FADE:
                    a = 0
                else:
                    edge = 1.0 - (rad - R_DISC) / (R_FADE - R_DISC)
                    edge = max(0.0, min(1.0, edge)) ** 1.4

                    a = int(min(1.0, lum * 1.35) * edge * 255)
            dst[x, y] = (r, g, b, a)

    sprite = rgba.resize((SPRITE, SPRITE), Image.LANCZOS)
    raw = sprite.tobytes()
    OUT_BIN.write_bytes(raw)

    OUT_RS.write_text(
        "// @generated by tools/bake_eclipse_sphere.py — DO NOT EDIT BY HAND.\n"
        "//\n"
        "// The OpenAI 3D eclipse sphere (assets/shell/eclipse-corona.png), pre-alpha'd and\n"
        "// downscaled to the orb's on-screen size, as a raw RGBA byte blob. shell.rs\n"
        "// alpha-blends it centred where the eclipse is — zero runtime dependency.\n"
        "\n"
        "/// Raw RGBA8888 (R,G,B,A), row-major top-to-bottom, %d x %d.\n"
        "pub static SPHERE_RGBA: &[u8] = include_bytes!(\"shell_sphere.bin\");\n"
        "/// Sprite edge length in pixels (square).\n"
        "pub const SPHERE_SIZE: usize = %d;\n" % (SPRITE, SPRITE, SPRITE)
    )
    print(f"wrote {OUT_BIN} ({len(raw)} bytes, {SPRITE}x{SPRITE} RGBA)")
    print(f"wrote {OUT_RS}")

if __name__ == "__main__":
    main()
