#!/usr/bin/env python3

import sys
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    sys.exit("PIL/Pillow required (build-time only): pip install pillow")

ROOT = Path(__file__).resolve().parent.parent
REDESIGN = ROOT / "assets" / "shell" / "redesign"

variant = "orb" if "--variant" in sys.argv and "orb" in sys.argv else "ghost"
SRC = REDESIGN / ("hero-phantom-orb.png" if variant == "orb" else "hero-phantom.png")

SPRITE = 300
if "--size" in sys.argv:
    try:
        SPRITE = int(sys.argv[sys.argv.index("--size") + 1])
    except (ValueError, IndexError):
        pass

OUT_BIN = ROOT / "src" / "shell_hero.bin"
OUT_RS = ROOT / "src" / "shell_hero.rs"

def main() -> None:
    im = Image.open(SRC).convert("RGBA")

    bbox = im.getchannel("A").getbbox()
    if bbox:
        im = im.crop(bbox)
    w, h = im.size
    side = max(w, h)
    pad = int(side * 0.06)
    side += 2 * pad
    square = Image.new("RGBA", (side, side), (0, 0, 0, 0))
    square.paste(im, ((side - w) // 2, (side - h) // 2), im)

    sprite = square.resize((SPRITE, SPRITE), Image.LANCZOS)
    raw = sprite.tobytes()
    OUT_BIN.write_bytes(raw)

    OUT_RS.write_text(
        "// @generated by tools/bake_phantom_hero.py — DO NOT EDIT BY HAND.\n"
        "//\n"
        "// The friendly phantom hero mascot (assets/shell/redesign/%s),\n"
        "// trimmed, centered and downscaled to the on-screen sprite size, as a raw RGBA\n"
        "// byte blob. shell.rs alpha-blends it centered where the hero sits — zero runtime\n"
        "// dependency. Replaces the old dark eclipse sphere (shell_sphere.rs).\n"
        "\n"
        "/// Raw RGBA8888 (R,G,B,A), row-major top-to-bottom, %d x %d.\n"
        "pub static HERO_RGBA: &[u8] = include_bytes!(\"shell_hero.bin\");\n"
        "/// Sprite edge length in pixels (square).\n"
        "pub const HERO_SIZE: usize = %d;\n" % (SRC.name, SPRITE, SPRITE, SPRITE)
    )
    print(f"variant={variant} src={SRC.name}")
    print(f"wrote {OUT_BIN} ({len(raw)} bytes, {SPRITE}x{SPRITE} RGBA)")
    print(f"wrote {OUT_RS}")

if __name__ == "__main__":
    main()
