#!/usr/bin/env python3

import sys
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    sys.exit("PIL/Pillow required (build-time only): pip install pillow")

ROOT = Path(__file__).resolve().parent.parent
REDESIGN = ROOT / "assets" / "shell" / "redesign"

NAMES = ["terminal", "files", "browser", "code", "claude", "settings", "calendar"]

ICON = 128
if "--size" in sys.argv:
    try:
        ICON = int(sys.argv[sys.argv.index("--size") + 1])
    except (ValueError, IndexError):
        pass

OUT_BIN = ROOT / "src" / "shell_icons.bin"
OUT_RS = ROOT / "src" / "shell_icons.rs"

def bake_one(path: Path) -> bytes:
    im = Image.open(path).convert("RGBA")
    bbox = im.getchannel("A").getbbox()
    if bbox:
        im = im.crop(bbox)
    w, h = im.size
    side = max(w, h)
    pad = int(side * 0.04)
    side += 2 * pad
    square = Image.new("RGBA", (side, side), (0, 0, 0, 0))
    square.paste(im, ((side - w) // 2, (side - h) // 2), im)
    sprite = square.resize((ICON, ICON), Image.LANCZOS)
    return sprite.tobytes()

def main() -> None:
    blob = bytearray()
    for name in NAMES:
        src = REDESIGN / f"icon-{name}.png"
        if not src.exists():
            sys.exit(f"missing source icon: {src}")
        raw = bake_one(src)
        assert len(raw) == ICON * ICON * 4, (name, len(raw))
        blob += raw
    OUT_BIN.write_bytes(blob)

    names_rs = ", ".join(f'"{n}"' for n in NAMES)
    OUT_RS.write_text(
        "// @generated by tools/bake_shell_icons.py — DO NOT EDIT BY HAND.\n"
        "//\n"
        "// The friendly comic launcher icons (assets/shell/redesign/icon-*.png),\n"
        "// each trimmed/centered/Lanczos-downscaled to ICON x ICON and concatenated\n"
        "// icon-major into one raw RGBA blob. shell.rs include_bytes!s it and alpha-\n"
        "// blends a chosen icon into a program-ring slot — zero runtime dependency.\n"
        "// Order mirrors PROGRAMS in shell.rs (Media dropped, Calendar in its slot).\n"
        "\n"
        "/// Raw RGBA8888 (R,G,B,A), row-major, %d icons of %d x %d, icon-major.\n"
        "pub static ICONS_RGBA: &[u8] = include_bytes!(\"shell_icons.bin\");\n"
        "/// Per-icon edge length in pixels (square).\n"
        "pub const ICON_SIZE: usize = %d;\n"
        "/// Number of icons in the atlas (== PROGRAMS.len()).\n"
        "pub const ICON_COUNT: usize = %d;\n"
        "/// Icon names, in atlas order (mirrors PROGRAMS in shell.rs).\n"
        "pub static ICON_NAMES: [&str; %d] = [%s];\n"
        % (len(NAMES), ICON, ICON, ICON, len(NAMES), len(NAMES), names_rs)
    )
    print(f"wrote {OUT_BIN} ({len(blob)} bytes, {len(NAMES)}x {ICON}x{ICON} RGBA)")
    print(f"wrote {OUT_RS}")

if __name__ == "__main__":
    main()
