#!/usr/bin/env python3

import struct
import sys
from pathlib import Path

try:
    from PIL import Image, ImageFont, ImageDraw
except ImportError:
    sys.exit("PIL/Pillow required: pip install Pillow")

ROOT = Path(__file__).resolve().parent.parent
MONO = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"
SANS_BOLD = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"

STYLES = [
    ("Caption",   MONO,      13),
    ("Body",      MONO,      16),
    ("Large",     MONO,      22),
    ("Heading",   SANS_BOLD, 19),
    ("HeadingXL", SANS_BOLD, 40),
]

ASCII = "".join(chr(c) for c in range(0x20, 0x7F))
SPECIAL = "·ÄäÖöÜüß§€—•…←↑→›↵▸⟶"

CHARSET = "".join(chr(c) for c in sorted({ord(c) for c in (ASCII + SPECIAL)}))

VARIANTS = ["Caption", "Body", "Large", "Heading", "HeadingXL"]

def main():
    atlas = bytearray()
    glyphs = []
    style_meta = []

    for style_idx, (name, font_path, px) in enumerate(STYLES):
        font = ImageFont.truetype(font_path, px)
        ascent, descent = font.getmetrics()
        line_height = ascent + descent
        space_adv = round(font.getlength(" "))
        style_meta.append((name, ascent, descent, line_height, space_adv))

        for ch in CHARSET:
            cp = ord(ch)
            advance = font.getlength(ch)
            bbox = font.getbbox(ch)
            if bbox is None or ch == " ":

                glyphs.append((style_idx, cp, 0, 0, 0, round(advance), 0, 0))
                continue
            x0, y0, x1, y1 = bbox
            w = x1 - x0
            h = y1 - y0
            if w <= 0 or h <= 0:
                glyphs.append((style_idx, cp, 0, 0, 0, round(advance), 0, 0))
                continue

            img = Image.new("L", (w, h), 0)
            draw = ImageDraw.Draw(img)
            draw.text((-x0, -y0), ch, font=font, fill=255)
            offset = len(atlas)
            atlas.extend(img.tobytes())

            bearing_top = ascent - y0
            glyphs.append((style_idx, cp, offset, w, h, round(advance), x0, bearing_top))

    bin_path = ROOT / "src" / "shell_font.bin"
    bin_path.write_bytes(bytes(atlas))

    rs = []
    rs.append("// @generated by tools/bake_font_atlas.py — DO NOT EDIT BY HAND.")
    rs.append("//")
    rs.append("// Grayscale anti-aliased glyph atlas for the phantom-shell renderer. The")
    rs.append("// runtime stays zero-dependency: this is a baked alpha-coverage blob")
    rs.append("// (`shell_font.bin`, include_bytes!-ed) plus a metrics table. `shell.rs`")
    rs.append("// alpha-blends each glyph over the background by its coverage byte.")
    rs.append("//")
    rs.append("// Fonts: DejaVu Sans Mono (body/caption/large) + DejaVu Sans Bold (headings).")
    rs.append("// Regenerate: `python3 tools/bake_font_atlas.py` from the repo root.")
    rs.append("")
    rs.append("/// The baked alpha-coverage atlas: one tight 8-bit bitmap per glyph, packed")
    rs.append("/// back-to-back. A `Glyph` indexes into this by `offset .. offset + w*h`.")
    rs.append("pub static ATLAS: &[u8] = include_bytes!(\"shell_font.bin\");")
    rs.append("")
    rs.append("/// A baked font style (one font at one pixel size).")
    rs.append("#[derive(Clone, Copy, PartialEq, Eq, Debug)]")
    rs.append("pub enum FontStyle {")
    for name in VARIANTS:
        rs.append(f"    {name},")
    rs.append("}")
    rs.append("")
    rs.append("/// Vertical metrics per style (pixels).")
    rs.append("#[derive(Clone, Copy)]")
    rs.append("pub struct StyleMetrics {")
    rs.append("    pub ascent: i32,")
    rs.append("    pub descent: i32,")
    rs.append("    pub line_height: i32,")
    rs.append("    pub space_advance: i32,")
    rs.append("}")
    rs.append("")
    rs.append("/// Per-style vertical metrics, indexed by `FontStyle as usize`.")
    rs.append(f"pub static STYLE_METRICS: [StyleMetrics; {len(style_meta)}] = [")
    for (name, ascent, descent, lh, sp) in style_meta:
        rs.append(f"    StyleMetrics {{ ascent: {ascent}, descent: {descent}, "
                  f"line_height: {lh}, space_advance: {sp} }}, // {name}")
    rs.append("];")
    rs.append("")
    rs.append("/// One baked glyph: where its coverage bitmap lives in `ATLAS` and how to")
    rs.append("/// place it. `bearing_y` is pixels from the baseline UP to the bitmap top.")
    rs.append("#[derive(Clone, Copy)]")
    rs.append("pub struct Glyph {")
    rs.append("    pub style: u8,")
    rs.append("    pub cp: u32,")
    rs.append("    pub offset: u32,")
    rs.append("    pub w: u16,")
    rs.append("    pub h: u16,")
    rs.append("    pub advance: i16,")
    rs.append("    pub bearing_x: i16,")
    rs.append("    pub bearing_y: i16,")
    rs.append("}")
    rs.append("")
    rs.append("/// All baked glyphs, grouped by style then ascending codepoint. The lookup in")
    rs.append("/// `shell.rs` binary-searches within a style's contiguous run.")
    rs.append(f"pub static GLYPHS: [Glyph; {len(glyphs)}] = [")
    for (si, cp, off, w, h, adv, bx, by) in glyphs:
        rs.append(
            f"    Glyph {{ style: {si}, cp: {cp}, offset: {off}, w: {w}, h: {h}, "
            f"advance: {adv}, bearing_x: {bx}, bearing_y: {by} }},"
        )
    rs.append("];")
    rs.append("")

    rs_path = ROOT / "src" / "shell_font.rs"
    rs_path.write_text("\n".join(rs))

    print(f"baked {len(glyphs)} glyphs across {len(STYLES)} styles")
    print(f"  atlas:   {bin_path}  ({len(atlas)} bytes)")
    print(f"  metrics: {rs_path}")

if __name__ == "__main__":
    main()
